name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Replace with your branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Specify your Node.js version


      # Step 3: Install dependencies and build the project
      - name: Install and Build
        run: |
          npm install
          npm run build
      
      #Step 4: Install Netlify CLI
      - name: Install Netlify CLI
        run: npm install -g netlify-cli   

      # Step 4: Deploy to Netlify
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PERSONAL_ACCESS_TOKEN }}
        run: netlify deploy --prod --dir=build
